// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Asset categorization AI agent.
 *
 * - categorizeAsset - A function that handles the asset categorization process.
 * - CategorizeAssetInput - The input type for the categorizeAsset function.
 * - CategorizeAssetOutput - The return type for the categorizeAsset function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CategorizeAssetInputSchema = z.object({
  description: z.string().describe('The description of the asset.'),
});
export type CategorizeAssetInput = z.infer<typeof CategorizeAssetInputSchema>;

const CategorizeAssetOutputSchema = z.object({
  category: z.string().describe('The predicted category of the asset.'),
  confidence: z.number().describe('The confidence level of the category prediction (0-1).'),
});
export type CategorizeAssetOutput = z.infer<typeof CategorizeAssetOutputSchema>;

export async function categorizeAsset(input: CategorizeAssetInput): Promise<CategorizeAssetOutput> {
  return categorizeAssetFlow(input);
}

const prompt = ai.definePrompt({
  name: 'categorizeAssetPrompt',
  input: {schema: CategorizeAssetInputSchema},
  output: {schema: CategorizeAssetOutputSchema},
  prompt: `You are an expert IT asset categorization specialist.

  Given the description of an asset, you will predict the most appropriate category for it and provide a confidence level for your prediction.

  Description: {{{description}}}
  `,
});

const categorizeAssetFlow = ai.defineFlow(
  {
    name: 'categorizeAssetFlow',
    inputSchema: CategorizeAssetInputSchema,
    outputSchema: CategorizeAssetOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
