
import type { Asset, Employee } from "@/types";

export const mockAssets: Asset[] = [
  {
    assetTag: "AST-1001",
    hostName: "Host-01",
    assetType: "Laptop",
    category: "Computer",
    make: "Dell",
    model: "XPS 15",
    serialNumber: "SN123456",
    processor: "Intel i7",
    os: "Windows",
    osVersion: "11 Pro",
    ram: "16GB",
    hddSsd: "512GB SSD",
    location: "HQ",
    status: "Assigned",
    assignedTo: "John Smith",
    remark: "Good condition",
    warrantyStatus: "Active",
    warrantyExpiration: "2026-05-01",
    value: 1500,
    history: [
      { date: "2024-04-15", type: "Software Installation", description: "Installed Adobe Creative Suite." },
      { date: "2024-01-10", type: "Maintenance", description: "Performed routine check-up." },
      { date: "2023-11-01", type: "Created", description: "Asset created and assigned to John Smith." },
    ],
  },
  {
    assetTag: "AST-1002",
    hostName: "Host-02",
    assetType: "Monitor",
    category: "Peripheral",
    make: "LG",
    model: "UltraGear",
    serialNumber: "SN234567",
    processor: "",
    os: "",
    osVersion: "",
    ram: "",
    hddSsd: "",
    location: "HQ",
    status: "Unassigned",
    assignedTo: "",
    remark: "New in box",
    warrantyStatus: "Active",
    warrantyExpiration: "2027-01-15",
    value: 450,
    history: [
       { date: "2024-02-20", type: "Created", description: "Asset registered in the system." },
    ]
  },
   {
    assetTag: "AST-1003",
    hostName: "Host-03",
    assetType: "Server",
    category: "Infrastructure",
    make: "HPE",
    model: "ProLiant DL380",
    serialNumber: "SN345678",
    processor: "Intel Xeon",
    os: "Windows Server",
    osVersion: "2022",
    ram: "64GB",
    hddSsd: "2TB SSD",
    location: "Data Center",
    status: "Under Maintenance",
    assignedTo: "",
    remark: "RAID array needs check",
    warrantyStatus: "Expired",
    warrantyExpiration: "2024-03-01",
    value: 5000,
    history: [
        { date: "2024-05-10", type: "Repair", description: "Replaced faulty power supply unit." },
        { date: "2022-03-01", type: "Created", description: "Server deployed to data center." },
    ],
  },
];

export const mockEmployees: Employee[] = [
  {
    id: "EMP-001",
    name: "Alice Johnson",
    email: "alice.j@example.com",
    department: "Engineering",
    title: "Software Engineer",
    status: "Active",
    avatarUrl: `https://i.pravatar.cc/150?u=a042581f4e29026024d`,
  },
  {
    id: "EMP-002",
    name: "Bob Williams",
    email: "bob.w@example.com",
    department: "Marketing",
    title: "Marketing Manager",
    status: "Active",
     avatarUrl: `https://i.pravatar.cc/150?u=a042581f4e29026704d`,
  },
  {
    id: "EMP-003",
    name: "Charlie Brown",
    email: "charlie.b@example.com",
    department: "Sales",
    title: "Sales Representative",
    status: "On Leave",
     avatarUrl: `https://i.pravatar.cc/150?u=a04258114e29026702d`,
  },
  {
    id: "EMP-004",
    name: "Diana Prince",
    email: "diana.p@example.com",
    department: "Human Resources",
    title: "HR Specialist",
    status: "Active",
     avatarUrl: `https://i.pravatar.cc/150?u=a048581f4e29026701d`,
  },
  {
    id: "EMP-005",
    name: "Ethan Hunt",
    email: "ethan.h@example.com",
    department: "Engineering",
    title: "QA Tester",
    status: "Terminated",
     avatarUrl: `https://i.pravatar.cc/150?u=a092581f4e29026705d`,
  },
];
