version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "80:8000"
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"   # Host port 3001 -> Container port 3000
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: